// Code generated by protoc-gen-go. DO NOT EDIT.
// source: distance.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	distance.proto

It has these top-level messages:
	UniqueId
	ResponseElement
	QueryResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UniqueId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *UniqueId) Reset()                    { *m = UniqueId{} }
func (m *UniqueId) String() string            { return proto.CompactTextString(m) }
func (*UniqueId) ProtoMessage()               {}
func (*UniqueId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UniqueId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResponseElement struct {
	Id   string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Dist float32 `protobuf:"fixed32,2,opt,name=dist" json:"dist,omitempty"`
}

func (m *ResponseElement) Reset()                    { *m = ResponseElement{} }
func (m *ResponseElement) String() string            { return proto.CompactTextString(m) }
func (*ResponseElement) ProtoMessage()               {}
func (*ResponseElement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseElement) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResponseElement) GetDist() float32 {
	if m != nil {
		return m.Dist
	}
	return 0
}

type QueryResponse struct {
	Response []*ResponseElement `protobuf:"bytes,1,rep,name=response" json:"response,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryResponse) GetResponse() []*ResponseElement {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*UniqueId)(nil), "api.UniqueId")
	proto.RegisterType((*ResponseElement)(nil), "api.ResponseElement")
	proto.RegisterType((*QueryResponse)(nil), "api.QueryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Distance service

type DistanceClient interface {
	Dist(ctx context.Context, in *UniqueId, opts ...grpc.CallOption) (*QueryResponse, error)
}

type distanceClient struct {
	cc *grpc.ClientConn
}

func NewDistanceClient(cc *grpc.ClientConn) DistanceClient {
	return &distanceClient{cc}
}

func (c *distanceClient) Dist(ctx context.Context, in *UniqueId, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/api.Distance/dist", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Distance service

type DistanceServer interface {
	Dist(context.Context, *UniqueId) (*QueryResponse, error)
}

func RegisterDistanceServer(s *grpc.Server, srv DistanceServer) {
	s.RegisterService(&_Distance_serviceDesc, srv)
}

func _Distance_Dist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniqueId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceServer).Dist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Distance/Dist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceServer).Dist(ctx, req.(*UniqueId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Distance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Distance",
	HandlerType: (*DistanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "dist",
			Handler:    _Distance_Dist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "distance.proto",
}

func init() { proto.RegisterFile("distance.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xc9, 0x2c, 0x2e,
	0x49, 0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54,
	0x92, 0xe2, 0xe2, 0x08, 0xcd, 0xcb, 0x2c, 0x2c, 0x4d, 0xf5, 0x4c, 0x11, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x51, 0x32, 0xe5, 0xe2, 0x0f,
	0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x75, 0xcd, 0x49, 0xcd, 0x4d, 0xcd, 0x2b, 0x41, 0x57,
	0x22, 0x24, 0xc4, 0xc5, 0x02, 0x32, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x29, 0x08, 0xcc, 0x56,
	0x72, 0xe4, 0xe2, 0x0d, 0x2c, 0x4d, 0x2d, 0xaa, 0x84, 0xe9, 0x15, 0x32, 0xe0, 0xe2, 0x28, 0x82,
	0xb2, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x12, 0x0b, 0x32, 0xf5, 0xd0, 0x0c,
	0x0f, 0x82, 0xab, 0x32, 0x32, 0xe7, 0xe2, 0x70, 0x81, 0x3a, 0x56, 0x48, 0x1b, 0x62, 0x85, 0x10,
	0x2f, 0x58, 0x0f, 0xcc, 0xb1, 0x52, 0x42, 0x60, 0x2e, 0x8a, 0x45, 0x4a, 0x0c, 0x49, 0x6c, 0x60,
	0xaf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x42, 0xc9, 0xe1, 0xed, 0xec, 0x00, 0x00, 0x00,
}
